# Generated by Django 5.2.1 on 2025-06-01 15:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název filmu musí být vyplněn'}, help_text='Zadejte název filmu', max_length=100, verbose_name='Název filmu')),
                ('obsah', models.TextField(blank=True, help_text='Vložte obsah filmu', verbose_name='Obsah filmu')),
                ('delka', models.PositiveIntegerField(blank=True, help_text='Zadejte délku filmu v minutách (max. 999)', null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Délka filmu')),
                ('rok_vydani', models.PositiveIntegerField(blank=True, help_text='Zadejte rok vydání (1895 - 2100)', null=True, validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok vydání')),
                ('plakat', models.ImageField(upload_to='plakaty', verbose_name='Plakát filmu')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmy',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Reziser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno režiséra musí být vyplněno'}, help_text='Zadejte jméno režiséra', max_length=80, verbose_name='Jméno režiséra')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení režiséra musí být vyplněno'}, help_text='Zadejte příjmení režiséra', max_length=50, verbose_name='Příjmení režiséra')),
                ('narozeni', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('umrti', models.DateField(blank=True, null=True, verbose_name='Datum úmrtí')),
                ('biografie', models.TextField(blank=True, verbose_name='Životopis')),
                ('fotografie', models.ImageField(upload_to='reziseri', verbose_name='Fotografie')),
            ],
            options={
                'verbose_name': 'Režisér',
                'verbose_name_plural': 'Režiséři',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název žánru', max_length=20, verbose_name='Název žánru')),
            ],
            options={
                'verbose_name': 'Žánr',
                'verbose_name_plural': 'Žánry',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Vložte text recenze', verbose_name='Text recenze')),
                ('upraveno', models.DateTimeField(auto_now=True, help_text='Datum poslední úpravy', verbose_name='Datum úpravy')),
                ('hodnoceni', models.IntegerField(choices=[(0, ''), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=3)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.film')),
                ('recenzent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recenze',
                'verbose_name_plural': 'Recenze',
                'ordering': ['-hodnoceni'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='reziseri',
            field=models.ManyToManyField(to='knihovna.reziser'),
        ),
        migrations.AddField(
            model_name='film',
            name='zanry',
            field=models.ManyToManyField(to='knihovna.zanr'),
        ),
    ]
